from .base_repo import *
from .user_repo import *
from .job_repo import *
from .personal_information_repo import *
from .expertise_mapper_repo import *
from .intrest_mapper_repo import *
from .skill_mapper_repo import *
from .gender_repo import *
from .nationality_repo import *
from .ethnicity_repo import *
from .country_repo import *
from .country_code_repo import *
from .state_repo import *
from .expertise_repo import *
from .skill_repo import *
from .intrest_repo import *
from .industry_repo import *
from .industry_mapper_repo import *
from .degree_repo import *
from .education_mapper_repo import *
from .experience_repo import *
from .native_language_repo import *
from .langugae_mapper_repo import *
from .language_repo import *
from .proficiency_repo import *
